version: '3.8'

services:
  db:
    image: postgres:13
    container_name: task_manager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

  app:
    build: .
    container_name: task_manager_app
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DATABASE_URL: "postgres://postgres:postgres@db:5432/task_manager"
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: ["mix", "phx.server"]

volumes:
  db_data:
